### ISSUE TITLE
jumpserver v3云同步创建的资产默认只有ssh没有sftp

### ISSUE THREAD

**Issue by PeterHgg** [starsliao/TenSunS#98]
这个需要逐个手动配置还是有点麻烦

**Comment by PeterHgg** [comment]
jumpserver支持lrzsz，好像也不是不能用。但是我在想是不是可以在全局特殊主机【管理用户】信息支持例如："linux": [
            ["ssh/22","sftp/22"],
            "b510418c-ea15-44d8-836a-5eb6138a6c56"
        ]

**Comment by jasonhu** [comment]
sftp传输文件内容，走的也是ssh协议。

你通过ssh工具，连接jumpserver的ssh代理端口的时候，该ssh代理帮你连接了目标主机的ssh，你就可以无秘钥/密码连接到目标主机并执行shell了。

不幸的时，jms的ssh代理功能，不支持sftp传输文件的代理。

在jms里面，建议的方式是通过jms的ui管理页面，将文件上传后，会自动放入到对应主机的tmp目录里。

因此该问题主要是jms自身的能力问题，和tensuns没有关系的。
